# Base Image
FROM node:20-alpine


WORKDIR /app


# Copy dependency files
COPY package*.json ./


# Install dependencies
RUN npm ci


# Copy source
COPY . .


# Build Next.js
RUN npm run build


ENV PORT=3000


EXPOSE 3000


# Production server
CMD ["npm", "start"]